version: '3.1'

services:
  frontend:
    build: './'
    volumes:
      - './src:/app/src'
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      CHOKIDAR_USEPOLLING: "true"
      DEVELOPMENT: ${DEVELOPMENT}
    ports:
      - 4200:4200